<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>University_Agent_System</RootNamespace>
    <UserSecretsId>288ef20f-c4d4-4f5b-8db5-ef797358da3a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin\**" />
    <Compile Remove="obj\**" />
    <Content Remove="bin\**" />
    <Content Remove="obj\**" />
    <EmbeddedResource Remove="bin\**" />
    <EmbeddedResource Remove="obj\**" />
    <None Remove="bin\**" />
    <None Remove="obj\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Models\DTO\ProgramDto.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="libphonenumber-csharp" Version="9.0.27" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Localization" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Localization.Routing" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.8.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
    <Folder Include="Models\DTO\" />
    <Folder Include="Resources\Controllers\HomeController\" />
  </ItemGroup>


</Project>
