// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using University_Agent_System.Data;

#nullable disable

namespace University_Agent_System.Migrations
{
    [DbContext(typeof(UASDbContext))]
    [Migration("20250226084146_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("University_Agent_System.Models.academicYear", b =>
                {
                    b.Property<int>("academicYearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("academicYearId"));

                    b.Property<int>("active")
                        .HasColumnType("int");

                    b.Property<string>("year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("academicYearId");

                    b.ToTable("AcademicYears");
                });

            modelBuilder.Entity("University_Agent_System.Models.agent", b =>
                {
                    b.Property<int>("agentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("agentId"));

                    b.Property<int>("active")
                        .HasColumnType("int");

                    b.Property<int>("agentCode")
                        .HasColumnType("int");

                    b.Property<string>("agentEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("agentIban")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("agentNameArabic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("agentNameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("agentPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("commission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("contractEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("contractStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("countryId")
                        .HasColumnType("int");

                    b.Property<int>("nationalityId")
                        .HasColumnType("int");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passowrd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("agentId");

                    b.HasIndex("nationalityId");

                    b.HasIndex("userId");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("University_Agent_System.Models.degree", b =>
                {
                    b.Property<int>("degreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("degreeId"));

                    b.Property<int>("active")
                        .HasColumnType("int");

                    b.Property<string>("degreeArabic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("degreeEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("degreeId");

                    b.ToTable("Degrees");
                });

            modelBuilder.Entity("University_Agent_System.Models.faculty", b =>
                {
                    b.Property<int>("facultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("facultyId"));

                    b.Property<int>("active")
                        .HasColumnType("int");

                    b.Property<string>("facultyNameArabic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("facultyNameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("facultyId");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("University_Agent_System.Models.nationality", b =>
                {
                    b.Property<int>("nationalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("nationalityId"));

                    b.Property<int>("active")
                        .HasColumnType("int");

                    b.Property<string>("nationalityArabic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nationalityEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("nationalityId");

                    b.ToTable("Nationalities");
                });

            modelBuilder.Entity("University_Agent_System.Models.program", b =>
                {
                    b.Property<int>("programId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("programId"));

                    b.Property<int>("active")
                        .HasColumnType("int");

                    b.Property<string>("programNameArabic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("programNameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("programId");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("University_Agent_System.Models.semester", b =>
                {
                    b.Property<int>("semesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("semesterId"));

                    b.Property<int>("active")
                        .HasColumnType("int");

                    b.Property<string>("semesterArabic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("semesterEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("yearId")
                        .HasColumnType("int");

                    b.HasKey("semesterId");

                    b.HasIndex("yearId");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("University_Agent_System.Models.status", b =>
                {
                    b.Property<int>("statusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("statusId"));

                    b.Property<int>("active")
                        .HasColumnType("int");

                    b.Property<string>("statusArabic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("statusEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("statusId");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("University_Agent_System.Models.student", b =>
                {
                    b.Property<int>("studentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("studentId"));

                    b.Property<int>("active")
                        .HasColumnType("int");

                    b.Property<int>("agentId")
                        .HasColumnType("int");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("countryId")
                        .HasColumnType("int");

                    b.Property<int>("degreeId")
                        .HasColumnType("int");

                    b.Property<int>("facultyId")
                        .HasColumnType("int");

                    b.Property<int>("isDiploma")
                        .HasColumnType("int");

                    b.Property<int>("isTransfer")
                        .HasColumnType("int");

                    b.Property<string>("nationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nationalityId")
                        .HasColumnType("int");

                    b.Property<int>("programId")
                        .HasColumnType("int");

                    b.Property<int>("semesterId")
                        .HasColumnType("int");

                    b.Property<int>("statusId")
                        .HasColumnType("int");

                    b.Property<string>("studentBachelor_Certification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentGPA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentGrades_Report")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentHigh_School_Certificate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentNameArabic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentNameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentPicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentProof_of_Identity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentSchool")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("studentId");

                    b.HasIndex("agentId");

                    b.HasIndex("degreeId");

                    b.HasIndex("facultyId");

                    b.HasIndex("nationalityId");

                    b.HasIndex("programId");

                    b.HasIndex("semesterId");

                    b.HasIndex("statusId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("University_Agent_System.Models.user", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<int>("active")
                        .HasColumnType("int");

                    b.Property<string>("userEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userNameArabic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userNameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userTypeId")
                        .HasColumnType("int");

                    b.HasKey("userId");

                    b.HasIndex("userTypeId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("University_Agent_System.Models.userType", b =>
                {
                    b.Property<int>("userTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userTypeId"));

                    b.Property<int>("active")
                        .HasColumnType("int");

                    b.Property<string>("userTypeArabic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userTypeEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userTypeId");

                    b.ToTable("UserTypes");
                });

            modelBuilder.Entity("University_Agent_System.Models.agent", b =>
                {
                    b.HasOne("University_Agent_System.Models.nationality", "Nationality")
                        .WithMany("Agents")
                        .HasForeignKey("nationalityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("University_Agent_System.Models.user", "User")
                        .WithMany("Agents")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Nationality");

                    b.Navigation("User");
                });

            modelBuilder.Entity("University_Agent_System.Models.semester", b =>
                {
                    b.HasOne("University_Agent_System.Models.academicYear", "AcademicYear")
                        .WithMany("Semesters")
                        .HasForeignKey("yearId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AcademicYear");
                });

            modelBuilder.Entity("University_Agent_System.Models.student", b =>
                {
                    b.HasOne("University_Agent_System.Models.agent", "Agent")
                        .WithMany("Students")
                        .HasForeignKey("agentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("University_Agent_System.Models.degree", "Degree")
                        .WithMany("Students")
                        .HasForeignKey("degreeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("University_Agent_System.Models.faculty", "Faculty")
                        .WithMany("Students")
                        .HasForeignKey("facultyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("University_Agent_System.Models.nationality", "Nationality")
                        .WithMany("Students")
                        .HasForeignKey("nationalityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("University_Agent_System.Models.program", "Program")
                        .WithMany("Students")
                        .HasForeignKey("programId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("University_Agent_System.Models.semester", "Semester")
                        .WithMany("Students")
                        .HasForeignKey("semesterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("University_Agent_System.Models.status", "Status")
                        .WithMany("Students")
                        .HasForeignKey("statusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Degree");

                    b.Navigation("Faculty");

                    b.Navigation("Nationality");

                    b.Navigation("Program");

                    b.Navigation("Semester");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("University_Agent_System.Models.user", b =>
                {
                    b.HasOne("University_Agent_System.Models.userType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("userTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("University_Agent_System.Models.academicYear", b =>
                {
                    b.Navigation("Semesters");
                });

            modelBuilder.Entity("University_Agent_System.Models.agent", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("University_Agent_System.Models.degree", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("University_Agent_System.Models.faculty", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("University_Agent_System.Models.nationality", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("University_Agent_System.Models.program", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("University_Agent_System.Models.semester", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("University_Agent_System.Models.status", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("University_Agent_System.Models.user", b =>
                {
                    b.Navigation("Agents");
                });

            modelBuilder.Entity("University_Agent_System.Models.userType", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
