// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using University_Agent_System.Data;

#nullable disable

namespace University_Agent_System.Migrations
{
    [DbContext(typeof(UASDbContext))]
    [Migration("20250420121654_RemoveOldTable")]
    partial class RemoveOldTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("University_Agent_System.Models.agent", b =>
                {
                    b.Property<int>("agentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("agentId"));

                    b.Property<int?>("active")
                        .HasColumnType("int");

                    b.Property<int?>("agentCode")
                        .HasColumnType("int");

                    b.Property<string>("agentEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("agentIban")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("agentNameArabic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("agentNameEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("agentPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("commission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("contractEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("contractStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("countryId")
                        .HasColumnType("int");

                    b.Property<string>("nationalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("nationalityId")
                        .HasColumnType("int");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passowrd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("userId")
                        .HasColumnType("int");

                    b.HasKey("agentId");

                    b.HasIndex("nationalityId");

                    b.HasIndex("userId");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("University_Agent_System.Models.degree", b =>
                {
                    b.Property<int>("degreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("degreeId"));

                    b.Property<int?>("active")
                        .HasColumnType("int");

                    b.Property<string>("degreeArabic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("degreeEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("degreeId");

                    b.ToTable("Degrees");
                });

            modelBuilder.Entity("University_Agent_System.Models.nationality", b =>
                {
                    b.Property<int>("nationalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("nationalityId"));

                    b.Property<int?>("active")
                        .HasColumnType("int");

                    b.Property<string>("nationalityArabic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nationalityEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("nationalityId");

                    b.ToTable("Nationalities");
                });

            modelBuilder.Entity("University_Agent_System.Models.status", b =>
                {
                    b.Property<int>("statusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("statusId"));

                    b.Property<int?>("active")
                        .HasColumnType("int");

                    b.Property<string>("statusArabic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("statusEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("statusId");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("University_Agent_System.Models.student", b =>
                {
                    b.Property<int>("studentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("studentId"));

                    b.Property<int?>("Faculty_no")
                        .HasColumnType("int");

                    b.Property<int?>("active")
                        .HasColumnType("int");

                    b.Property<int?>("agentId")
                        .HasColumnType("int");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("countryId")
                        .HasColumnType("int");

                    b.Property<int?>("degreeId")
                        .HasColumnType("int");

                    b.Property<int?>("isDiploma")
                        .HasColumnType("int");

                    b.Property<int?>("isTransfer")
                        .HasColumnType("int");

                    b.Property<int?>("major_no")
                        .HasColumnType("int");

                    b.Property<string>("nationalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("nationalityId")
                        .HasColumnType("int");

                    b.Property<int?>("semesterId")
                        .HasColumnType("int");

                    b.Property<int?>("statusId")
                        .HasColumnType("int");

                    b.Property<string>("studentBachelor_Certification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentGPA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("studentGender")
                        .HasColumnType("int");

                    b.Property<string>("studentGrades_Report")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentHigh_School_Certificate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentNameArabic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentNameEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentPicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentProof_of_Identity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentSchool")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("studentId");

                    b.HasIndex("agentId");

                    b.HasIndex("degreeId");

                    b.HasIndex("nationalityId");

                    b.HasIndex("statusId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("University_Agent_System.Models.user", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<int?>("active")
                        .HasColumnType("int");

                    b.Property<string>("userEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userNameArabic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userNameEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("userTypeId")
                        .HasColumnType("int");

                    b.HasKey("userId");

                    b.HasIndex("userTypeId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("University_Agent_System.Models.userType", b =>
                {
                    b.Property<int>("userTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userTypeId"));

                    b.Property<int?>("active")
                        .HasColumnType("int");

                    b.Property<string>("userTypeArabic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userTypeEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userTypeId");

                    b.ToTable("UserTypes");
                });

            modelBuilder.Entity("University_Agent_System.Models.agent", b =>
                {
                    b.HasOne("University_Agent_System.Models.nationality", "Nationality")
                        .WithMany("Agents")
                        .HasForeignKey("nationalityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("University_Agent_System.Models.user", "User")
                        .WithMany("Agents")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Nationality");

                    b.Navigation("User");
                });

            modelBuilder.Entity("University_Agent_System.Models.student", b =>
                {
                    b.HasOne("University_Agent_System.Models.agent", "Agent")
                        .WithMany("Students")
                        .HasForeignKey("agentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("University_Agent_System.Models.degree", "Degree")
                        .WithMany("Students")
                        .HasForeignKey("degreeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("University_Agent_System.Models.nationality", "Nationality")
                        .WithMany("Students")
                        .HasForeignKey("nationalityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("University_Agent_System.Models.status", "Status")
                        .WithMany("Students")
                        .HasForeignKey("statusId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Agent");

                    b.Navigation("Degree");

                    b.Navigation("Nationality");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("University_Agent_System.Models.user", b =>
                {
                    b.HasOne("University_Agent_System.Models.userType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("userTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("University_Agent_System.Models.agent", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("University_Agent_System.Models.degree", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("University_Agent_System.Models.nationality", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("University_Agent_System.Models.status", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("University_Agent_System.Models.user", b =>
                {
                    b.Navigation("Agents");
                });

            modelBuilder.Entity("University_Agent_System.Models.userType", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
